spring.application.name=qr-attendance

server.address=0.0.0.0
server.port=8080

spring.datasource.url = jdbc:mysql://localhost:3306/qr_code_attendance
spring.datasource.password = Sandeep@73
spring.datasource.username = root

spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true

# Registration code
student.registration.code = STU8113
teacher.registration.code = TCH8181